name = "aws-devops-quiz-app"
compatibility_date = "2025-03-24"
compatibility_flags = ["nodejs_compat"]

# Environment variables
[vars]
NODE_ENV = "production"
NEXT_PUBLIC_API_URL = "/api"

# Cloudflare Pages configuration (required format)
[pages]
build.command = "npm install --legacy-peer-deps && npm run build && npm run build:worker && npm run post-build"
build.output_dir = ".output/public"  # Cloudflare Pages expected output directory
pages_build_output_dir = ".output/public"

# Site configuration
[site]
bucket = ".output/public"

# Routes configuration
[[routes]]
pattern = "/api/*"

# Asset handling rules
[[rules]]
globs = ["**/*.pdf"]
type = "asset"

# D1 Database configuration
[[d1_databases]]
binding = "DB"
database_name = "aws-quiz-app-db"
database_id = "def7f03b-c291-4016-a126-163dbccd88a5"

# R2 Storage configuration
[[r2_buckets]]
binding = "STORAGE"